package io.multiplatform.swift.sdk.util

import java.io.File

/**
 * Generates a temporary iOS-compatible Package.swift by stripping
 * Android-only dependencies (e.g. swift-java) that don't support iOS.
 *
 * This replaces the shell-script-based Package.swift swapping approach
 * from the prototype.
 */
object PackageSwiftGenerator {

    /**
     * Generates an iOS-only Package.swift from a template.
     *
     * @param outputFile Where to write the generated manifest
     * @param moduleName Swift module name
     * @param iosPlatformVersion iOS deployment target (e.g. "15")
     * @param iosDependencies List of (url, minVersion) pairs for iOS-safe dependencies
     */
    fun generate(
        outputFile: File,
        moduleName: String,
        iosPlatformVersion: String,
        iosDependencies: List<Pair<String, String>> = emptyList(),
    ) {
        val iosVer = iosPlatformVersion.substringBefore(".")

        val depsBlock = if (iosDependencies.isEmpty()) "" else {
            iosDependencies.joinToString("\n        ") { (url, ver) ->
                ".package(url: \"$url\", from: \"$ver\"),"
            }
        }

        val targetDepsBlock = if (iosDependencies.isEmpty()) "" else {
            iosDependencies.joinToString("\n                ") { (url, _) ->
                val name = url.substringAfterLast("/").removeSuffix(".git")
                ".product(name: \"${name.replaceFirstChar { it.uppercase() }}\", package: \"$name\"),"
            }
        }

        val content = buildString {
            appendLine("// swift-tools-version: 6.2")
            appendLine("// Generated by swift-multiplatform Gradle plugin — iOS build only.")
            appendLine("// This file is temporary and will be restored after the build.")
            appendLine("import PackageDescription")
            appendLine()
            appendLine("let package = Package(")
            appendLine("    name: \"$moduleName\",")
            appendLine("    platforms: [.iOS(.v$iosVer), .macOS(.v12)],")
            appendLine("    products: [")
            appendLine("        .library(name: \"$moduleName\", targets: [\"$moduleName\"]),")
            appendLine("    ],")
            if (depsBlock.isNotEmpty()) {
                appendLine("    dependencies: [")
                appendLine("        $depsBlock")
                appendLine("    ],")
            }
            appendLine("    targets: [")
            if (targetDepsBlock.isNotEmpty()) {
                appendLine("        .target(name: \"$moduleName\", dependencies: [")
                appendLine("            $targetDepsBlock")
                appendLine("        ]),")
            } else {
                appendLine("        .target(name: \"$moduleName\"),")
            }
            appendLine("    ]")
            appendLine(")")
        }

        outputFile.writeText(content)
    }

    /**
     * Parses a Package.swift file and extracts SPM dependency URLs and versions.
     * Returns pairs of (url, version) for dependencies that are NOT in the strip list.
     */
    fun extractIosDependencies(
        packageSwift: File,
        stripDependencies: List<String> = listOf("swift-java"),
    ): List<Pair<String, String>> {
        val content = packageSwift.readText()
        val depPattern = Regex("""\.\s*package\s*\(\s*url:\s*"([^"]+)"\s*,\s*from:\s*"([^"]+)"\s*\)""")

        return depPattern.findAll(content).mapNotNull { match ->
            val url = match.groupValues[1]
            val version = match.groupValues[2]
            val repoName = url.substringAfterLast("/").removeSuffix(".git")

            if (stripDependencies.any { repoName.contains(it, ignoreCase = true) }) {
                null  // Strip this dependency
            } else {
                url to version
            }
        }.toList()
    }
}
